Add notification to volume state changes
OdiousImp2604/openbox pull request #4
Opened 2021-09-11 13:31 UTC by ParanoidNemo

Add notification using dunstify when changing volume state

openbox/scripts
- add volume script for up, down and mute

rc.xml
- assign script to media keybindings

2021-09-11 14:41 UTC, flyingcakes85 reviewed
We could combine those three scripts into one.

```sh
#!/bin/bash

msgId="991002"

if [ "$1" = "up" ]; then
    amixer -q set Master 5%+ unmute
    volume=$(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master))
elif [ "$1" = "down" ]; then
    amixer -q set Master 5%- unmute
    volume=$(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master))
elif [ "$1" = "toggle" ]; then
    amixer -D pulse sset Master toggle-mute
    volume=$(awk -F"[][]" '/Left:/ { print $4 }' <(amixer sget Master))
fi

dunstify -u low -r "$msgId" "Volume $volume"

```

And then call it by these

```sh
./volume.sh up         # increase volume
./volume.sh down       # decrease volume
./volume.sh toggle     # toggle
```

2021-09-11 14:41 UTC, flyingcakes85 commented on .config/openbox/scripts/volume-mute
> +amixer -D pulse sset Master toggle-mute && volume=$(awk -F"[][]" '/Left:/ { print $6 }' <(amixer sget Master)) && dunstify -u low -r "$msgId" "Volume $volume"
> volume=$(awk -F"[][]" '/Left:/ { print $6 }' <(amixer sget Master))

This doesn't store anything to `volume` on my system. Maybe you meant to use `print $4` that would store `on` or `off`.

2021-09-12 07:12 UTC, ParanoidNemo commented on .config/openbox/scripts/volume-mute
> +amixer -D pulse sset Master toggle-mute && volume=$(awk -F"[][]" '/Left:/ { print $6 }' <(amixer sget Master)) && dunstify -u low -r "$msgId" "Volume $volume"
strange, on mine store on or off, I've tested before committing because on my main I use pamixer instead of amixer and the command are different. I'm on a VM tho, I don't know if that change things.

2021-09-13 02:27 UTC, flyingcakes85 requested changes
The brightness scripts can be merged as such

```sh
#!/bin/bash

msgId="991001"

if [ "$1" = "up" ]; then
    xbacklight -inc 5
elif [ "$1" = "down"]
    xbacklight -dec 5
fi

dunstify -u low -r "$msgId" "Brightness $(xbacklight -get | cut -d . -f 1)%"

```

Please use this script for brightness and the above posted one for volume, and add a new commit.

Thanks

2021-09-13 06:02 UTC, ParanoidNemo commented
> The brightness scripts can be merged as such
> 
> ```shell
> #!/bin/bash
> 
> msgId="991001"
> 
> if [ "$1" = "up" ]; then
>     xbacklight -inc 5
> elif [ "$1" = "down"]
>     xbacklight -dec 5
> fi
> 
> dunstify -u low -r "$msgId" "Brightness $(xbacklight -get | cut -d . -f 1)%"
> ```
> 
> Please use this script for brightness and the above posted one for volume, and add a new commit.
> 
> Thanks

Sure thing! I'm sorry but I had add that commit to the pull request before seeing your reply on the previous. I'll modify those. Only thing that I would like confirmation is that `print $4` or `print $6` thing in volume script because for me works only with `print $6` but seems to be broken for you. I'll check if can be done differently so that works in any case.

2021-09-13 06:39 UTC, flyingcakes85 commented
@ParanoidNemo 
For the time being use whatever works on your system. Mine is an old installation and that could be causing the issue.
Don't worry about the commits, I can squash them before merge.

2021-09-13 19:07 UTC, ParanoidNemo commented
uploaded new commit with requested changes

2021-09-14 02:53 UTC, flyingcakes85 approved these changes
Looks good now :)

2021-09-14 02:54 UTC, flyingcakes85 commented
Thanks for the PR!
 Megring

2021-09-14 02:55 UTC, merged

2021-09-14 02:59 UTC, flyingcakes85 commented
@ParanoidNemo 
For future pull requests, I highly recommend creating a new branch on your local machine and adding commits to that. When done, push that branch on GitHub and create PR from that new branch. This will avoid extra commit named `Merge branch 'OdiousImp2604:main' into main` to seep into the PR.

For updating the main branch of your fork, you could rebase it to the `main` branch. Simply pulling might add another such commit since you added commits to your main branch.